######################################################################
# Automatically generated by qmake (3.0) Rab Des 28 13:03:46 2016
######################################################################
QT += widgets 
TEMPLATE = app
TARGET = htmltag
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
